project_id = "qutcchpywpxcjbfcgdlq"

[functions.spin-wheel]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.check-spin-rate-limit]
verify_jwt = false

[functions.get-visitor-analytics]
verify_jwt = false