// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  process.env.NODE_ENV === "development"
    ? "http://localhost:54321"
    : "https://qutcchpywpxcjbfcgdlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dGNjaHB5d3B4Y2piZmNnZGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDEzMTMsImV4cCI6MjA3MTc3NzMxM30.Gz-7cW9cxnEn4Pk8_MMm3NyInzQIubLVXSBt5QUtec0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
